### ISSUE TITLE
GT should consistently have file extensions

### ISSUE THREAD

**Issue by tboenig** [OCR-D/assets#35] opened 2019-07-11 15:05 UTC
Files referenced in the METS and stored in the data directory should have file extensions to make life easier for PAGE Viewer etc.

**Comment by bertsky** [comment] 2019-07-11 16:34
I totally agree. We have started to make this a pattern in the processors (preprocessing, OCR), but IMO core should lead by good example in `Workspace.add_file` – at least if no `local_filename` was already specified by the caller – and in the bagger (see OCR-D/core#258).

**Comment by kba** [comment] 2019-07-11 17:40
Implementing OCR-D/core#258 will most likely fix this since the extensions are present until bagging...

**Comment by bertsky** [comment] 2019-07-11 18:02
Yes, but processors that do not care about this and do not use `local_filename` when doing their `Workspace.add_file` currently _also_ effectively suppress extensions. This case is still in core's responsibility.

**Comment by kba** [comment] 2019-07-11 18:12
You're right, I just meant that for our provided GT the problem is the bagger. Workspace.add_file must be fixed too ofc.

**Comment by bertsky** [comment] 2019-07-11 20:54
Oh, now I got it. We just keep agreeing you know!

**Comment by wrznr** [comment] 2019-10-23 13:34
@kba Fixed?

**Comment by kba** [comment] 2019-10-23 13:47
It's fixed for the bagger but I'm still evaluating whether

> when doing their Workspace.add_file currently also effectively suppress extensions. This case is still in core's responsibility.

is still an issue in core.

**Comment by kba** [comment] 2019-10-23 15:38
> Yes, but processors that do not care about this and do not use local_filename when doing their Workspace.add_file currently also effectively suppress extensions. 

Not sure whether I can follow. Can you give me an example when this might happen @bertsky ?

**Comment by bertsky** [comment] 2019-10-23 16:23
> > Yes, but processors that do not care about this and do not use local_filename when doing their Workspace.add_file currently also effectively suppress extensions.
> 
> Not sure whether I can follow. Can you give me an example when this might happen @bertsky ?

I can't see it myself right now. What I do understand is that `Workspace.add_file` does not in itself require either the `local_filename` or `url` kwarg, especially if it does not pass a `content` with it. So `OcrdMets.add_file` will instantiate a new `OcrdFile` and then set `local_filename=None`.

So it all depends on what then happens with that file reference later-on in the processor. If `content` was passed to `Workspace.add_file`, then an exception will come up. (I have already [complained](https://github.com/OCR-D/core/issues/96#issuecomment-513375558) about this as a documentation issue.) Otherwise, the processor might use `OcrdMets.find_files` to get a reference and then do things to it. Somewhere along that path `local_filename` will/must be set. There we have to look whether it is in core's responsibility to ensure filename extensions.

Sorry, that's all I can offer ATM.

**Comment by cneud** [comment] 2021-02-04 01:36
It appears all file extensions are available now in assets/data, a related issue https://github.com/OCR-D/core/issues/332 in core was closed - can this be closed too?

**Comment by kba** [comment] 2021-02-04 10:13
Yes, fixed in assets and we're doing file extensions in the processors now as well.

**Closed by kba** 2021-02-04 10:13 UTC
Labels: groundtruth
