### ISSUE TITLE
comparison between the contents of the <Word> elements and the <TextEquivType><Unicode> elements : Schematron

### ISSUE THREAD

**Issue by tboenig** [OCR-D/assets#16] opened 2018-09-17 13:49 UTC
It can happen that a comparison between the content of the elements `<Word>` and `<TextEquiv><Unicode>` detects differences. To check any differences a schematron is necessary.

**Comment by bertsky** [comment] 2018-09-17 14:44
You surely mean between some element's `TextEquiv:Unicode` and its sub-component element's `TextEquiv:Unicode`, as in:
- between `TextRegion` and its `TextLine` sequence
- between `TextLine` and its `Word` sequence
- between `Word` and its `Glyph` sequence

Should the consistency principle not be added to the [spec](https://github.com/OCR-D/spec) in PAGE.md?

I sometimes use XSL transformations to concatenate sub-components (joining them by whitespace or newline, depending on position) – maybe this is a good starting point for such schematron. If you think those would in fact be useful, where can I put them?

(But then again, why not add a function to `WorkspaceValidator.validate()` in core instead?)

**Comment by kba** [comment] 2018-09-17 14:59
> Should the consistency principle not be added to the spec in PAGE.md?

It should.

> Why not add a function to WorkspaceValidator.validate() in core instead?

We could. Preferably define it in the spec first and then implement it referring to it.

**Comment by bertsky** [comment] 2018-10-30 10:10
Shouldn't we at least start an issue on core to support PAGE-related consistency in `WorkspaceValidator.validate()` before closing here? The problem is that we might have to actually look at the GT data in order to get the consistency principle right in the details. See [this comment](https://github.com/OCR-D/assets/issues/13#issuecomment-422069829).

**Comment by kba** [comment] 2018-12-18 17:48
Implemented in https://github.com/OCR-D/core/pull/223

**Closed by kba** 2018-12-18 17:48 UTC
